version: '3'
services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: .
      args:
        VIRON_VERSION: v1.3.0
    ports:
      - 8080:8080
    environment:
      SHELL: /bin/bash
  backend:
    build:
      dockerfile: backend.Dockerfile
      context: .
    tty: true
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - ./.aws:/home/node/.aws
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
  db:
    build:
      dockerfile: backend.Dockerfile
      context: .
    tty: true
    command: yarn dev:db
    ports:
      - 8000:8000
    volumes:
      - ./.aws:/home/node/.aws
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
