name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Packages
        run: yarn

      - name: Inject Secrets
        run: |
          cat src/env.example.yml | \
            sed -e 's/YOUR_COGNITO_USERPOOL_ID/${{ secrets.ENV_COGNITO_USERPOOL_ID }}/g' | \
            sed -e 's;YOUR_COGNITO_USERPOOL_BASE_URL;${{ secrets.ENV_COGNITO_BASE_URL }};g' | \
            sed -e 's/YOUR_COGNITO_USERPOOL_CLIENT_ID/${{ secrets.ENV_COGNITO_CLIENT_ID }}/g' | \
            sed -e 's/YOUR_COGNITO_USERPOOL_CLIENT_SECRET/${{ secrets.ENV_COGNITO_CLIENT_SECRET }}/g' | \
            sed -e 's/YOUR_ADMINISTRATOR_IAM_USER/${{ secrets.ENV_ADMINISTRATOR_IAM_USER }}/g' | \
            sed -e 's;YOUR_KINTAI_WEBSITE_URL;${{ secrets.ENV_KINTAI_WEBSITE_URL }};g' \
              > src/env.prod.yml

      - name: Build and Deploy
        run: yarn release:prod
